var Sequelize = require('sequelize');
var db = require('../_db');

module.exports = db.define('user', {
  //id generated by sequelize
  //userId added by making association with userModel
    items: {
      type: Sequelize.ARRAY(Sequelize.TEXT),
    }
  }, {
    instanceMethods: {
      addToCart: function(friendId){
        this.items.push(friendId);
      }
    }
});
