var Sequelize = require('sequelize');
var db = require('../_db');

module.exports = db.define('cart', {
  //id generated by sequelize
  //userId added by making association with userModel
    items: {
      type: Sequelize.JSON,
      get: function() {
          return JSON.parse(this.getDataValue('items'));
      },
      set: function(val) {
          return this.setDataValue('items', JSON.stringify(val));
      }
    }
  }, {
    instanceMethods: {
      addToCart: function(friendId){
        this.items.push(friendId);
      }
    }
});
